In [49]:
import pandas as pd
from sqlalchemy import create_engine,text

In [50]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("Kaishu@1626")

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost:3306/superstore_db"
)

print("✅ Connected successfully!")

✅ Connected successfully!

In [51]:
query = "SELECT * FROM Cleaned_Superstore LIMIT 5;"

df = pd.read_sql(query, engine)

df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [52]:
import pandas as pd

df = pd.read_csv("../data/Cleaned_Superstore.csv")
print(df.head())

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156  2016-11-08  2016-11-11    Second Class    CG-12520
1       2  CA-2016-152156  2016-11-08  2016-11-11    Second Class    CG-12520
2       3  CA-2016-138688  2016-06-12  2016-06-16    Second Class    DV-13045
3       4  US-2015-108966  2015-10-11  2015-10-18  Standard Class    SO-20335
4       5  US-2015-108966  2015-10-11  2015-10-18  Standard Class    SO-20335

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases
1       42420   South  FUR-CH-10000454        Furniture       Chairs
2       90036    West  OFF-LA-10000240  Office Supplies       Labels
3       33311   South  FUR-TA-10000577        Furniture       Tables
4       33311   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]

In [53]:
import pandas as pd

df = pd.read_csv("../data/Cleaned_Superstore.csv")

print(df.shape)
df.head()

(9994, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [54]:
df.to_sql(
    name="cleaned_superstore",
    con=engine,
    if_exists="replace",
    index=False
)

print("✅ Table imported successfully!")

✅ Table imported successfully!

In [55]:
pd.read_sql("SELECT COUNT(*) FROM cleaned_superstore;", engine)

   COUNT(*)
0      9994

In [56]:
query = "SELECT * FROM cleaned_superstore LIMIT 10;"
df1 = pd.read_sql(query, engine)
df1

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

In [57]:
query = """
SELECT Category,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM cleaned_superstore
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

df2 = pd.read_sql(query, engine)
df2

          Category  Total_Sales
0       Technology    836154.03
1        Furniture    741999.80
2  Office Supplies    719047.03

In [58]:
query = """
SELECT `Product Name`,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM cleaned_superstore
GROUP BY `Product Name`
ORDER BY Total_Sales DESC
LIMIT 10;
"""

df3 = pd.read_sql(query, engine)
df3

                                        Product Name  Total_Sales
0              Canon imageCLASS 2200 Advanced Copier     61599.82
1  Fellowes PB500 Electric Punch Plastic Comb Bin...     27453.38
2  Cisco TelePresence System EX90 Videoconferenci...     22638.48
3       HON 5400 Series Task Chairs for Big and Tall     21870.58
4         GBC DocuBind TL300 Electric Binding System     19823.48
5   GBC Ibimaster 500 Manual ProClick Binding System     19024.50
6               Hewlett Packard LaserJet 3310 Copier     18839.69
7  HP Designjet T520 Inkjet Large Format Printer ...     18374.90
8          GBC DocuBind P400 Electric Binding System     17965.07
9        High Speed Automatic Electric Letter Opener     17030.31

In [59]:
query = """
SELECT Region,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM cleaned_superstore
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

df4 = pd.read_sql(query, engine)
df4

    Region  Total_Sales
0     West    725457.82
1     East    678781.24
2  Central    501239.89
3    South    391721.91

In [60]:
query = """
SELECT Segment,
       ROUND(AVG(Profit),2) AS Average_Profit
FROM cleaned_superstore
GROUP BY Segment;
"""

df5 = pd.read_sql(query, engine)
df5

       Segment  Average_Profit
0     Consumer           25.84
1    Corporate           30.46
2  Home Office           33.82

# SQL Fundamentals

view first 10 rows

In [61]:
query = """
SELECT *
FROM cleaned_superstore
LIMIT 10;
"""

pd.read_sql(query, engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

Sales greater than 1000

In [62]:
query = """
SELECT *
FROM cleaned_superstore
WHERE Sales > 1000;
"""

pd.read_sql(query, engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,11,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.184,9,0.2,85.3092
1,25,CA-2015-106320,2015-09-25,2015-09-30,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,...,84057,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.630,3,0.0,240.2649
2,28,US-2015-150630,2015-09-17,2015-09-21,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430,7,0.5,-1665.0522
3,36,CA-2016-117590,2016-12-08,2016-12-10,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,...,75080,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544,7,0.2,123.4737
4,55,CA-2016-105816,2016-12-11,2016-12-17,Standard Class,JM-15265,Janet Molinari,Corporate,United States,New York City,...,10024,East,TEC-PH-10002447,Technology,Phones,AT&T CL83451 4-Handset Telephone,1029.950,5,0.0,298.6855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,9867,US-2015-116981,2015-03-26,2015-03-28,Second Class,SM-20950,Suzanne McNair,Corporate,United States,New York City,...,10009,East,OFF-ST-10002615,Office Supplies,Storage,"Dual Level, Single-Width Filing Carts",1085.420,7,0.0,282.2092
464,9926,CA-2015-159534,2015-03-20,2015-03-23,First Class,DH-13075,Dave Hallsten,Corporate,United States,New York City,...,10035,East,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,1087.936,8,0.2,353.5792
465,9930,CA-2016-129630,2016-09-04,2016-09-04,Same Day,IM-15055,Ionia McGrath,Consumer,United States,San Francisco,...,94122,West,TEC-CO-10003763,Technology,Copiers,Canon PC1060 Personal Laser Copier,2799.960,5,0.2,944.9865
466,9948,CA-2017-121559,2017-06-01,2017-06-03,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,46203,Central,FUR-CH-10003746,Furniture,Chairs,Hon 4070 Series Pagoda Round Back Stacking Chairs,1925.880,6,0.0,539.2464
467,9949,CA-2017-121559,2017-06-01,2017-06-03,Second Class,HW-14935,Helen Wasserman,Corporate,United States,Indianapolis,...,46203,Central,OFF-AP-10002945,Office Supplies,Appliances,Honeywell Enviracaire Portable HEPA Air Cleane...,2405.200,8,0.0,793.7160

Top 10 highest sales

In [63]:
query = """
SELECT *
FROM cleaned_superstore
ORDER BY Sales DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,2698,CA-2014-145317,2014-03-18,2014-03-23,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,32216,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784
1,6827,CA-2016-118689,2016-10-02,2016-10-09,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
2,8154,CA-2017-140151,2017-03-23,2017-03-25,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808
3,2624,CA-2017-127180,2017-10-22,2017-10-24,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,10024,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888
4,4191,CA-2017-166709,2017-11-17,2017-11-22,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856
5,9040,CA-2016-117121,2016-12-17,2016-12-21,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Detroit,...,48205,Central,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.740,13,0.0,4946.3700
6,4099,CA-2014-116904,2014-09-23,2014-09-28,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Minneapolis,...,55407,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.950,5,0.0,4630.4755
7,4278,US-2016-107440,2016-04-16,2016-04-20,Standard Class,BS-11365,Bill Shonely,Corporate,United States,Lakewood,...,8701,East,TEC-MA-10001047,Technology,Machines,"3D Systems Cube Printer, 2nd Generation, Magenta",9099.930,7,0.0,2365.9818
8,8489,CA-2016-158841,2016-02-02,2016-02-04,Second Class,SE-20110,Sanjit Engle,Consumer,United States,Arlington,...,22204,South,TEC-MA-10001127,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,8749.950,5,0.0,2799.9840
9,6426,CA-2016-143714,2016-05-23,2016-05-27,Standard Class,CC-12370,Christopher Conant,Consumer,United States,Philadelphia,...,19120,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,8399.976,4,0.4,1119.9968

Total Sales by Category

In [64]:
query = """
SELECT Category,
SUM(Sales) AS Total_Sales
FROM cleaned_superstore
GROUP BY Category;
"""

pd.read_sql(query, engine)

          Category  Total_Sales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330

Categories having sales above ₹500000

In [65]:
query = """
SELECT Category,
SUM(Sales) AS Total_Sales
FROM cleaned_superstore
GROUP BY Category
HAVING SUM(Sales) > 500000;
"""

pd.read_sql(query, engine)

          Category  Total_Sales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330

Top 5 Products by Sales (Business Question)

In [66]:
query = """
SELECT `Product Name`,
SUM(Sales) AS Total_Sales
FROM cleaned_superstore
GROUP BY `Product Name`
ORDER BY Total_Sales DESC
LIMIT 5;
"""

pd.read_sql(query, engine)

                                        Product Name  Total_Sales
0              Canon imageCLASS 2200 Advanced Copier    61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...    27453.384
2  Cisco TelePresence System EX90 Videoconferenci...    22638.480
3       HON 5400 Series Task Chairs for Big and Tall    21870.576
4         GBC DocuBind TL300 Electric Binding System    19823.479

Monthly Sales Trend

In [67]:
query = """
SELECT
MONTH(`Order Date`) AS Month,
SUM(Sales) AS Total_Sales
FROM cleaned_superstore
GROUP BY MONTH(`Order Date`)
ORDER BY Month;
"""

pd.read_sql(query, engine)

    Month  Total_Sales
0       1   94924.8356
1       2   59751.2514
2       3  205005.4888
3       4  137762.1286
4       5  155028.8117
5       6  152718.6793
6       7  147238.0970
7       8  159044.0630
8       9  307649.9457
9      10  200322.9847
10     11  352461.0710
11     12  325293.5035

Customer Spending

In [68]:
query = """
SELECT
`Customer Name`,
SUM(Sales) AS Total_Spent
FROM cleaned_superstore
GROUP BY `Customer Name`
ORDER BY Total_Spent DESC
LIMIT 10;
"""

pd.read_sql(query, engine)

        Customer Name  Total_Spent
0         Sean Miller    25043.050
1        Tamara Chand    19052.218
2        Raymond Buch    15117.339
3        Tom Ashbrook    14595.620
4       Adrian Barton    14473.571
5        Ken Lonsdale    14175.229
6        Sanjit Chand    14142.334
7        Hunter Lopez    12873.298
8        Sanjit Engle    12209.438
9  Christopher Conant    12129.072

SUBQUERY

In [69]:
query = """
SELECT `Product Name`, Sales
FROM cleaned_superstore
WHERE Sales > (
    SELECT AVG(Sales)
    FROM cleaned_superstore
)
ORDER BY Sales DESC;
"""

pd.read_sql(query, engine)

                                           Product Name      Sales
0     Cisco TelePresence System EX90 Videoconferenci...  22638.480
1                 Canon imageCLASS 2200 Advanced Copier  17499.950
2                 Canon imageCLASS 2200 Advanced Copier  13999.960
3                 Canon imageCLASS 2200 Advanced Copier  11199.968
4                 Canon imageCLASS 2200 Advanced Copier  10499.970
...                                                 ...        ...
2355                         Bevis Steel Folding Chairs    230.280
2356                         Bevis Steel Folding Chairs    230.280
2357                         Bevis Steel Folding Chairs    230.280
2358                         Bevis Steel Folding Chairs    230.280
2359      Space Solutions HD Industrial Steel Shelving.    229.940

[2360 rows x 2 columns]

CTE (WITH Clause)

In [70]:
query = """
WITH CategorySales AS (
    SELECT Category,
           SUM(Sales) AS Total_Sales
    FROM cleaned_superstore
    GROUP BY Category
)

SELECT *
FROM CategorySales
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, engine)

          Category  Total_Sales
0       Technology  836154.0330
1        Furniture  741999.7953
2  Office Supplies  719047.0320

ROW_NUMBER()

In [71]:
query = """
SELECT
    `Product Name`,
    Category,
    Sales,
    ROW_NUMBER() OVER(
        ORDER BY Sales DESC
    ) AS Row_Num
FROM cleaned_superstore;
"""

pd.read_sql(query, engine)

,Product Name,Category,Sales,Row_Num
0,Cisco TelePresence System EX90 Videoconferenci...,Technology,22638.480,1
1,Canon imageCLASS 2200 Advanced Copier,Technology,17499.950,2
2,Canon imageCLASS 2200 Advanced Copier,Technology,13999.960,3
3,Canon imageCLASS 2200 Advanced Copier,Technology,11199.968,4
4,Canon imageCLASS 2200 Advanced Copier,Technology,10499.970,5
...,...,...,...,...
9989,Acco 3-Hole Punch,Office Supplies,0.876,9990
9990,Avery Round Ring Poly Binders,Office Supplies,0.852,9991
9991,Avery Durable Slant Ring Binders With Label Ho...,Office Supplies,0.836,9992
9992,Acco Suede Grain Vinyl Round Ring Binder,Office Supplies,0.556,9993
9993,Hoover Replacement Belt for Commercial Guardsm...,Office Supplies,0.444,9994

RANK()

In [72]:
query = """
SELECT
    `Product Name`,
    Sales,
    RANK() OVER(
        ORDER BY Sales DESC
    ) AS Sales_Rank
FROM cleaned_superstore;
"""

pd.read_sql(query, engine)

                                           Product Name      Sales  Sales_Rank
0     Cisco TelePresence System EX90 Videoconferenci...  22638.480           1
1                 Canon imageCLASS 2200 Advanced Copier  17499.950           2
2                 Canon imageCLASS 2200 Advanced Copier  13999.960           3
3                 Canon imageCLASS 2200 Advanced Copier  11199.968           4
4                 Canon imageCLASS 2200 Advanced Copier  10499.970           5
...                                                 ...        ...         ...
9989                                  Acco 3-Hole Punch      0.876        9990
9990                      Avery Round Ring Poly Binders      0.852        9991
9991  Avery Durable Slant Ring Binders With Label Ho...      0.836        9992
9992           Acco Suede Grain Vinyl Round Ring Binder      0.556        9993
9993  Hoover Replacement Belt for Commercial Guardsm...      0.444        9994

[9994 rows x 3 columns]

LAG()

In [73]:
query = """
SELECT
    `Order Date`,
    Sales,
    LAG(Sales) OVER(
        ORDER BY `Order Date`
    ) AS Previous_Sales
FROM cleaned_superstore;
"""

pd.read_sql(query, engine)

      Order Date    Sales  Previous_Sales
0     2014-01-03   16.448             NaN
1     2014-01-04    3.540          16.448
2     2014-01-04  272.736           3.540
3     2014-01-04   11.784         272.736
4     2014-01-05   19.536          11.784
...          ...      ...             ...
9989  2017-12-30   20.720          13.904
9990  2017-12-30   52.776          20.720
9991  2017-12-30  209.300          52.776
9992  2017-12-30   90.930         209.300
9993  2017-12-30    3.024          90.930

[9994 rows x 3 columns]

LEAD()

In [74]:
query = """
SELECT
    `Order Date`,
    Sales,
    LEAD(Sales) OVER(
        ORDER BY `Order Date`
    ) AS Next_Sales
FROM cleaned_superstore;
"""

pd.read_sql(query, engine)

      Order Date    Sales  Next_Sales
0     2014-01-03   16.448       3.540
1     2014-01-04    3.540     272.736
2     2014-01-04  272.736      11.784
3     2014-01-04   11.784      19.536
4     2014-01-05   19.536    2573.820
...          ...      ...         ...
9989  2017-12-30   20.720      52.776
9990  2017-12-30   52.776     209.300
9991  2017-12-30  209.300      90.930
9992  2017-12-30   90.930       3.024
9993  2017-12-30    3.024         NaN

[9994 rows x 3 columns]

Create a View

In [75]:
query = """
CREATE VIEW category_sales AS

SELECT
    Category,
    SUM(Sales) AS Total_Sales
FROM cleaned_superstore
GROUP BY Category;
"""

with engine.begin() as conn:
    conn.execute(text(query))

print("✅ View Created Successfully!")

✅ View Created Successfully!

View the View

In [76]:
query = """
SELECT *
FROM category_sales;
"""

pd.read_sql(query, engine)

          Category  Total_Sales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330

1. JOIN Example

In [77]:
query = """
CREATE TABLE customer_info (
    `Customer ID` VARCHAR(20) PRIMARY KEY,
    Email VARCHAR(100)
);
"""

with engine.begin() as conn:
    conn.execute(text(query))

print("Customer table created.")

Customer table created.

In [78]:
query = """
INSERT INTO customer_info (`Customer ID`, Email)
VALUES
('CG-12520','claire@example.com'),
('DV-13045','darrin@example.com'),
('SO-20335','sean@example.com');
"""

with engine.begin() as conn:
    conn.execute(text(query))

print("Sample data inserted.")

Sample data inserted.

INNER JOIN

In [79]:
query = """
SELECT
cs.`Customer Name`,
ci.Email,
cs.Sales

FROM cleaned_superstore cs

INNER JOIN customer_info ci
ON cs.`Customer ID` = ci.`Customer ID`;
"""

pd.read_sql(query, engine)

      Customer Name               Email     Sales
0       Claire Gute  claire@example.com  261.9600
1       Claire Gute  claire@example.com  731.9400
2   Darrin Van Huff  darrin@example.com   14.6200
3    Sean O'Donnell    sean@example.com  957.5775
4    Sean O'Donnell    sean@example.com   22.3680
5   Darrin Van Huff  darrin@example.com  188.5520
6    Sean O'Donnell    sean@example.com   28.4400
7    Sean O'Donnell    sean@example.com  364.4100
8    Sean O'Donnell    sean@example.com   39.9600
9    Sean O'Donnell    sean@example.com  361.7640
10   Sean O'Donnell    sean@example.com    8.8320
11   Sean O'Donnell    sean@example.com  177.5360
12   Sean O'Donnell    sean@example.com  258.4800
13   Sean O'Donnell    sean@example.com   14.1360
14  Darrin Van Huff  darrin@example.com    4.0800
15  Darrin Van Huff  darrin@example.com   18.9000
16      Claire Gute  claire@example.com   18.1600
17  Darrin Van Huff  darrin@example.com   19.5200
18      Claire Gute  claire@example.com  131.3760
19      Claire Gute  claire@example.com    5.3440
20   Sean O'Donnell    sean@example.com  154.9000
21   Sean O'Donnell    sean@example.com   41.8600
22   Sean O'Donnell    sean@example.com  141.9600
23  Darrin Van Huff  darrin@example.com  721.8750
24  Darrin Van Huff  darrin@example.com   73.5680
25  Darrin Van Huff  darrin@example.com   13.5840
26  Darrin Van Huff  darrin@example.com   64.7840
27   Sean O'Donnell    sean@example.com   18.6880
28   Sean O'Donnell    sean@example.com   11.6640